services:
  nextjs-app:
    build: .
    container_name: nextjs-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
