name: prodCI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BLOG_API_URL: https://instakash-blog.herokuapp.com
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      CONTENT_API_KEY: ${{ secrets.CONTENT_API_KEY }}
      FB_PIXEL_ID: ${{ secrets.FB_PIXEL_ID }}
      AWS_REGION: us-east-2
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build de application
        run: yarn build
      - name: Build admin om netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: false
          build_directory: "out"
