name: prodCI

on:
  push:
    paths-ignore: [.github/**]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BLOG_API_URL: https://instakash-blog.herokuapp.com
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      CONTENT_API_KEY: ${{ secrets.CONTENT_API_KEY }}
      FB_PIXEL_ID: ${{ secrets.FB_PIXEL_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build de application
        run: yarn build
